### ISSUE TITLE
Granting Permissions to aws-kf-ci-bot

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/internal-acls#348]
First section is [aws-kf-ci-bot](https://github.com/aws-kf-ci-bot) account is used to delegate AWS prow to run tests against PR.

So there are two options to grant permissions to aws-kf-ci-bot for some repos.

1. Add one section [here](https://github.com/kubeflow/internal-acls/blob/561ca6c8232b988978b66abc079aec598abc3e0c/github-orgs/kubeflow/org.yaml#L719)

```
          aws-ci-bots:
            description: Team for AWS bots
            members:
            - aws-kf-ci-bot
            privacy: closed
            repos:
              caffe2-operator: write
              katib: write
              mpi-operator: write
              mxnet-operator: write
              pytorch-operator: write
              tf-operator: write
              xgboost-operator: write
``` 

2. For Training and AutoML WG's repositories, we can manually add aws-kf-ci-bot account into collaborator.

Another section is about managing webhook in repo-level. 

I was thinking about using prow/hmac tool to manage webhook, and found 

```
To run this tool, you'll need:

1. A github account that has admin permission to the orgs/repos.
...

Ref: https://github.com/kubernetes/test-infra/tree/1dd7c15ee5952ec573744ae4075956049aa71f3a/prow/cmd/hmac
```
Given it requires admin access for aws-kf-ci-bot to kubeflow repos, I don't think prow/hmac is able to solve the problem for now.

So I think we can manually add webhook into some repos.
