### ISSUE TITLE
aws-kf-ci-bot don't have write access to specified repos

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/internal-acls#361]
Given the merged PR https://github.com/kubeflow/internal-acls/pull/353, 

```
          third-party-bots:
            description: Team for third party bots
            members:
            - aws-kf-ci-bot
            privacy: closed
            repos:
              katib: write
              pytorch-operator: write
```
`aws-kf-ci-bot` account should have write access to katib and pytorch-operator repos.

Obviously, the `third-party-bots` team don't have access to both repos:

https://github.com/orgs/kubeflow/teams/third-party-bots/repositories

How can we fix the issue? I think it's blocking issue for Kubeflow Shared Test-infra POC, because bot account can't report Github Status.

/cc @chensun @jlewi @Bobgy @Jeffwan @andreyvelich
